//
//  ResultsVC.swift
//  bramptonHackathon
//
//  Created by Jaden Scali on 2022-07-30.
//

import UIKit

class ResultsVC: UIViewController {
    
    @IBOutlet weak var typeText: UILabel!
    @IBOutlet var superView: UIView!
    @IBOutlet weak var biotext: UILabel!
    
    var recyclableIteams: [String] = [
        "plastic water bottle",
        "aluminum can",
        "aluminum foil plate",
        "aluminum trays and liners",
        "antifreeze - empty container",
        "applesauce, jello and pudding cups (single serving)",
        "aseptic container or box (soy, milk, juice, water, soup, drinks)",
        "black plastic takeout trays",
        "boxboard",
        "bread bag",
        "bristol board or flip chart paper",
        "broken glass from jars and bottles",
        "calendar",
        "cardboard box, basket or carton",
        "catalogue",
        "cereal, pasta or cakemix box",
        "clear plastic egg carton",
        "coffee can",
        "computer paper",
        "construction and craft paper",
        "cookie, chocolate, toffee or biscuit tin",
        "cottage cheese tub",
        "dairy tubs and lids",
        "detergent box",
        "dry cleaning bag",
        "empty prescription bottles",
        "envelope (with plastic window)",
        "envelope (without plastic window)",
        "file folders",
        "flyers",
        "foam egg cartons",
        "food and snack cans (aluminum, steel, paperboard)",
        "frozen dinner plastic food tray",
        "frozen vegetable bag",
        "gift bag (rope removed, non metallic)",
        "gift boxes",
        "gift wrapping paper (non-metallic)",
        "glass bottle",
        "glass coffee jar",
        "glass jar",
        "greeting card (without foil)",
        "hardcover book, bound journal or notebook",
        "household cleanser bottle",
        "household paper or printed papers",
        "iced cappuccino, shush or slurpy cup and lid",
        "index card",
        "juice box",
        "junk mail",
        "kleenex box",
        "magazines or catalogues",
        "metal bottles and cans (empty)",
        "metal coffee can",
        "metal paint cans with metal handles (empty)",
        "milk bags or transparent bags",
        "milk carton",
        "newspaper",
        "packing paper",
        "paper egg carton and takeout coffee trays",
        "paper ice cream carton or tub",
        "paper roll and coffee cup sleeves",
        "paperboard or spiral cans",
        "phone book",
        "pizza box (empty)",
        "plastic beer cups or plates",
        "plastic beverage container",
        "plastic clamshell packaging for fruit, vegetables or baked goods",
        "plastic coffee container",
        "plastic cookie, cracker, or chocolate trays",
        "plastic film overwrap on goods in cases",
        "plastic food and drink containers or Tupperware",
        "plastic food packaging",
        "plastic grocery or retail bags",
        "plastic ice cream tub",
        "plastic jar",
        "plastic jug for detergent, laundry soap or fabric softener",
        "plastic packaging and bottles",
        "plastic packaging including clam shell containers, domed lids and plastic liners",
        "plastic pail (smaller than 5 litres)",
        "plastic paint cans with plastic handles (empty)",
        "plastic plant, flower pots, flats, seed-starter trays",
        "plastic sandwich bag or food packaging",
        "plastic soap bottle",
        "plastic water bottles",
        "polystyrene and thermocol containers and plates",
        "polystyrene coffee cups",
        "postcard",
        "posters",
        "prepared food box",
        "printed paper",
        "produce and bulk food bags",
        "shampoo bottle",
        "shoe box",
        "sour cream, cottage cheese or cheese spread tub",
        "steel can",
        "sticky notes",
        "tissue box",
        "tissue wrapping paper, Crepe paper and streamers",
        "toiletpaper tube",
        "water bottle",
        "wax carton",
        "white (granulated) paper sugar bags",
        "white styrofoam packaging",
        "writing paper",
        "yogurt beverage container",
        "yogurt tub and lids"
    ]
    
    var compostIteams: [String] = [
        "banana",
        "Apple",
        "Apricot",
        "Avocado",
        "Banana",
        "Blackberry",
        "Blueberry",
        "Cherry",
        "Coconut",
        "Cucumber",
        "Durian",
        "Dragonfruit",
        "Fig",
        "Gooseberry",
        "Grape",
        "Guava",
        "Jackfruit",
        "Plum",
        "Kiwifruit",
        "Kumquat",
        "Lemon",
        "Lime",
        "Mango",
        "Watermelon",
        "Mulberry",
        "Orange",
        "Papaya",
        "Passionfruit",
        "Peach",
        "Pear",
        "Persimmon",
        "Pineapple",
        "Pineberry",
        "Quince",
        "Raspberry",
        "Soursop",
        "Star fruit",
        "Strawberry",
        "Tamarind",
        "Yuzu",
        "artichoke",
        "aubergine",
        "asparagus",
        "legumes",
        "alfalfa",
        "beans",
        "azuki beans",
        "bean sprouts",
        "black beans",
        "black-eyed peas",
        "borlotti bean",
        "broad beans",
        "chickpeas",
        "green beans",
        "kidney beans",
        "lentils",
        "lima beans",
        "mung beans",
        "navy beans",
        "peanuts",
        "pinto beans",
        "runner beans",
        "split peas",
        "soy beans",
        "peas",
        "mange tout",
        "broccoflower",
        "broccoli",
        "brussels sprouts",
        "cabbage",
        "kohlrabi",
        "Savoy cabbage",
        "red cabbage",
        "cauliflower",
        "celery",
        "endive",
        "fiddleheads",
        "frisee",
        "fennel",
        "greens",
        "bok choy",
        "chard",
        "collard greens",
        "kale",
        "mustard greens",
        "herbs",
        "anise",
        "basil",
        "caraway",
        "coriander",
        "chamomile",
        "daikon",
        "dill",
        "fennel",
        "lavender",
        "cymbopogon",
        "marjoram",
        "oregano",
        "parsley",
        "rosemary",
        "thyme",
        "lettuce",
        "arugula",
        "mushrooms",
        "Nettles",
        "spinach",
        "New Zealand spinach",
        "okra",
        "onions",
        "chives",
        "garlic",
        "leek",
        "onion",
        "shallot",
        "scallion",
        "peppers",
        "bell pepper",
        "chili pepper",
        "jalapeno",
        "habanero",
        "paprika",
        "tabasco pepper",
        "cayenne pepper",
        "radicchio",
        "rhubarb",
        "root vegetables",
        "beetroot",
        "mangel-wurzel",
        "carrot",
        "celeriac",
        "corms",
        "eddoe",
        "konjac",
        "taro",
        "water chestnut",
        "ginger",
        "parsnip",
        "Rutabaga",
        "radish",
        "wasabi",
        "horseradish",
        "daikon",
        "tubers",
        "jicama",
        "jerusalem artichoke",
        "potato",
        "sweet potato",
        "yam",
        "turnip",
        "salsify",
        "skirret",
        "sweetcorn",
        "topinambur",
        "squashes",
        "acorn squash",
        "bitter melon",
        "butternut squash",
        "banana squash",
        "courgette",
        "cucumber",
        "delicata",
        "gem squash",
        "hubbard squash",
        "Marrow",
        "Squash",
        "spaghetti squash",
        "zucchini",
        "spinach",
        "tat soi",
        "tomato",
        "watercress",
        "Turnips",
        "eggshells",
        "coffee",
        "tea",
        "grass"

    ]
    
    override func viewDidLoad() {
    super.viewDidLoad()

        // Do any additional setup after loading the view
        
        let recyclingBios: [String] = [
            "\(currentObjectName)s can go in the blue bin. after that, it will be processed and turned into something new! this is good for the environment because it reduces waste in landfills.",
            "\(currentObjectName)s can go in the blue bin. plastic is a common recylable item, but less than 10% of it is recycled. thank you for helping to increase recycling rates."
        ]
        
        let compostBios: [String] = [
            "\(currentObjectName)s can go in the green bin. compost is used to create soil fertilizer, which grows healthy plants! this is fantastic for the environment, so continue to use compostable items.",
            "\(currentObjectName)s can go in the green bin. tn the u.s., only about 4% of food waste is composted every year. thanks to you, that number is going to increase!"
        ]
        
        let garbageBios: [String] = [
            "\(currentObjectName)s must go in the garbage bin. then, it will be dumped into a landfill, which pollutes the earth and harms the environment. try your best to avoid using items which go in the trash.",
            "\(currentObjectName)s must go in the garbage bin. landfills produce about 25% of canada's methane emissions, which contributes to global warming. try to avoid using items which ends up in the garbage."
        ]
        
        let ranNum = Int.random(in: 0...recyclingBios.count - 1)
        
        if recyclableIteams.contains(currentObjectName.lowercased()) {
            print ("is recycle")
            typeText.text = "recycle"
            biotext.text = recyclingBios[ranNum]
            superView.backgroundColor = #colorLiteral(red: 0.3960784314, green: 0.5568627451, blue: 0.6117647059, alpha: 1)
        } else if compostIteams.contains(currentObjectName.lowercased()) {
            print ("is compost")
            typeText.text = "compost"
            biotext.text = compostBios[ranNum]
            superView.backgroundColor = UIColor.systemBrown
        } else {
            print("is garbage")
            typeText.text = "garbage"
            biotext.text = garbageBios[ranNum]
            superView.backgroundColor = .darkGray
        }
    }
}
